Fix bug found while reviewing patch for issue #1601. This bug was blocking my review of the patch.
Looks like an outdated use of date:datetag. name and formatOrder attributes were causing problems. Specifically...

REPRO:
1. add custom date field for groups (use any settings)
2. add a new group
3. try to edit that group's information

java.lang.IllegalStateException: Date formatOrder is invalid: date=02/02/1901, year=02/02/1901, month=, day=
	org.mifos.framework.struts.tags.DateTag.getDayMonthYear(DateTag.java:174)

All unit tests pass and test deployment succeeded.

git-svn-id: https://mifos.svn.sourceforge.net/svnroot/mifos/trunk@12719 a8845c50-7012-0410-95d3-8e1449b9b1e4