Reverted r14535... ran into some problems running unit tests. Full stacktrace follows. Note that another problem was masking the stacktrace below when executing the run_test Ant target (possibly conflicting versions of Ant... the currently running one and the one used by junit??). Only by setting fork="false" were we able to get the stacktrace.
org.mifos.application.accounts.financial.exceptions.FinancialException: org.mifos.application.accounts.financial.exceptions.FinancialException: org.mifos.application.configuration.exceptions.ConfigurationException: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'configuration'.
	at org.mifos.application.accounts.financial.util.helpers.FinancialInitializer.initialize(FinancialInitializer.java:82)
	at org.mifos.framework.util.helpers.TestCaseInitializer.<clinit>(TestCaseInitializer.java:60)
	at org.mifos.framework.MifosTestCase.<clinit>(MifosTestCase.java:51)
	at org.mifos.config.ConfigTestSuite.suite(ConfigTestSuite.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.AllTests.testFromSuiteMethod(AllTests.java:36)
	at org.junit.runners.AllTests.<init>(AllTests.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.junit.internal.requests.ClassRequest.buildRunner(ClassRequest.java:33)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:28)
	at org.junit.runners.Suite.<init>(Suite.java:55)
	at org.junit.runners.Suite.<init>(Suite.java:41)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.junit.internal.requests.ClassRequest.buildRunner(ClassRequest.java:33)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:28)
	at junit.framework.JUnit4TestAdapter.<init>(JUnit4TestAdapter.java:28)
	at junit.framework.JUnit4TestAdapter.<init>(JUnit4TestAdapter.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:386)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeInVM(JUnitTask.java:1339)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:831)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:1785)
	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:785)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:357)
	at org.apache.tools.ant.Target.performTasks(Target.java:385)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1337)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1306)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1189)
	at org.apache.tools.ant.Main.runBuild(Main.java:758)
	at org.apache.tools.ant.Main.startAnt(Main.java:217)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:257)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:104)
Caused by: org.mifos.application.accounts.financial.exceptions.FinancialException: org.mifos.application.configuration.exceptions.ConfigurationException: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'configuration'.
	at org.mifos.application.accounts.financial.util.helpers.FinancialInitializer.loadCOA(FinancialInitializer.java:120)
	at org.mifos.application.accounts.financial.util.helpers.FinancialInitializer.initialize(FinancialInitializer.java:71)
	... 50 more
Caused by: org.mifos.application.configuration.exceptions.ConfigurationException: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'configuration'.
	at org.mifos.config.ChartOfAccountsConfig.load(ChartOfAccountsConfig.java:108)
	at org.mifos.application.accounts.financial.util.helpers.FinancialInitializer.loadCOA(FinancialInitializer.java:117)
	... 51 more
Caused by: org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'configuration'.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
	at org.apache.xerces.jaxp.validation.DOMValidatorHelper.beginNode(Unknown Source)
	at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
	at org.apache.xerces.jaxp.validation.DOMValidatorHelper.validate(Unknown Source)
	at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source)
	at javax.xml.validation.Validator.validate(Validator.java:127)
	at org.mifos.config.ChartOfAccountsConfig.load(ChartOfAccountsConfig.java:102)
	... 52 more


git-svn-id: https://mifos.svn.sourceforge.net/svnroot/mifos/trunk@14536 a8845c50-7012-0410-95d3-8e1449b9b1e4