CollectionSheetEntryAction#getClientAttendance() appears to be breaking. This is what I see in my Mifos.log file:
2009-10-06/04:44:27.018/CDT ERROR, org.mifos.application.collectionsheet, CollectionSheetEntryAction, getClientAttendance, 549, Unexpected error getting Client Attendance.
org.mifos.framework.exceptions.ServiceException: org.mifos.framework.exceptions.PersistenceException: Could not find attendance for clientId 8 and meeting date Thu Feb 05 00:00:00 CST 2009
        at org.mifos.application.customer.client.business.service.StandardClientService.getClientAttendance(StandardClientService.java:71)
        at org.mifos.application.collectionsheet.struts.action.CollectionSheetEntryAction.getClientAttendance(CollectionSheetEntryAction.java:547)
        at org.mifos.application.collectionsheet.struts.action.CollectionSheetEntryAction.get(CollectionSheetEntryAction.java:275)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.struts.actions.DispatchAction.dispatchMethod(DispatchAction.java:274)
        at org.apache.struts.actions.DispatchAction.execute(DispatchAction.java:194)
        at org.mifos.framework.struts.action.BaseAction.execute(BaseAction.java:90)
        at org.mifos.framework.struts.action.MifosRequestProcessor.processActionPerform(MifosRequestProcessor.java:203)
        at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:224)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1194)
        at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:432)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.mifos.framework.security.util.LoginFilter.doFilter(LoginFilter.java:91)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.mifos.framework.persistence.DatabaseInitFilter.doFilter(DatabaseInitFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:568)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:286)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:845)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:447)
        at java.lang.Thread.run(Thread.java:619)
Caused by: org.mifos.framework.exceptions.PersistenceException: Could not find attendance for clientId 8 and meeting date Thu Feb 05 00:00:00 CST 2009
        at org.mifos.application.accounts.loan.persistance.StandardClientAttendanceDao.getAttendance(StandardClientAttendanceDao.java:50)
        at org.mifos.application.customer.client.business.service.StandardClientService.getClientAttendance(StandardClientService.java:68)
        ... 34 more

git-svn-id: https://mifos.svn.sourceforge.net/svnroot/mifos/trunk@15028 a8845c50-7012-0410-95d3-8e1449b9b1e4