Revert fix for MIFOS-4854, it broke the build:
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.3:run (native2ascii) on project mifos-webapp: An Ant BuildException has occured: Error starting Sun's native2ascii

http://ci.mifos.org/hudson/view/mifos-builds/job/head-master-commit/149/console

This reverts commit 23544ec43dcd0119d248ad6bdae446c52b3d191e.