Merged revisions 15890,15895 via svnmerge from https://mifos.dev.java.net/svn/mifos/branches/api-midstream
........
  r15890 | meonkeys | 2009-10-08 13:40:00 -0700 (Thu, 08 Oct 2009) | 8 lines
  
  In progress. Currently throws:
      java.lang.NoClassDefFoundError: org/mifos/spi/TransactionImport
  
  * pull plugin classnames from application-wide configuration file
  * use reflection to instantiate plugins
  * dynamically populate dropdown with available import plugins
  * renamed importTransactionsType to importPluginName 
........
  r15895 | meonkeys | 2009-10-08 16:29:51 -0700 (Thu, 08 Oct 2009) | 1 line
  
  add FIXMEs to PluginManager for strings that need to be externalized
........


git-svn-id: https://mifos.svn.sourceforge.net/svnroot/mifos/trunk@15897 a8845c50-7012-0410-95d3-8e1449b9b1e4